---
title: "Machine Learning - Classification of weight lifting excercises"
author: "gunbra"
date: "March 21, 2015"
output: html_document
---

```{r, echo = FALSE, results='hide'}
library(ggplot2)
library(caret)
```


```{r, fig.height = 2.,fig.width = 3., echo = FALSE, cache=FALSE, results='hide'}

testing <- read.csv("pml-testing.csv",na.strings = c("NA", "na", "NULL",
                                                     "null", ""))
training <- read.csv("pml-training.csv",na.strings = c("NA", "na", "NULL",
                                                      "null", ""))
itrain <- createDataPartition(training$classe,p=.99,list=FALSE)
train_test <- training[-itrain,]
train_train <- training[itrain,]
ii <- nearZeroVar(train_train,freqCut=70/30,uniqueCut=20)
t1 <- train_train[,-ii]
t1 <- t1[,colSums(is.na(t1))<1]
t1 <- t1[,c(-1,-2,-3,-4,-5,-6,-7)]
```

```{r, fig.height = 2.,fig.width = 3., echo = FALSE, cache=TRUE}

fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 20)
fit <-train(classe ~ . ,data=t1, method="rf",ntree=50)
ps <- predict(fit,train_test)
confusionMatrix(ps,train_test$classe)
```

```{r, fig.height = 2.,fig.width = 3., echo = FALSE, cache=FALSE, results='hide'}
varImp(fit,scale=TRUE)
```

```{r, fig.height = 5.,fig.width = 3., echo = FALSE, cache=FALSE, results='hide'}
varImpPlot(fit$finalModel)
```
